In [1]:
import pandas as pd

In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [3]:
import numpy as np

In [33]:
Arrhythmia= pd.read_csv('data/arrhythmia.csv.csv', header=None)
Arrhythmia.head(10)

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
5,13,0,169,51,100,167,321,174,91,107,...,-0.6,12.2,-2.8,0.0,0.0,0.9,2.2,13.5,31.1,14
6,40,1,160,52,77,129,377,133,77,77,...,0.0,6.5,0.0,0.0,0.0,0.4,1.0,14.3,20.5,1
7,49,1,162,54,78,0,376,157,70,67,...,0.0,8.2,-1.9,0.0,0.0,0.1,0.5,15.8,19.8,1
8,44,0,168,56,84,118,354,160,63,61,...,0.0,7.0,-1.3,0.0,0.0,0.6,2.1,12.5,30.9,1
9,50,1,167,67,89,130,383,156,73,85,...,-0.6,10.8,-1.7,0.0,0.0,0.8,0.9,20.1,25.1,10

In [5]:
Arrhythmia.shape

(452, 280)

In [6]:
Arrhythmia.head()

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7

In [7]:
Arrhythmia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Columns: 280 entries, 0 to 279
dtypes: float64(120), int64(155), object(5)
memory usage: 988.9+ KB

In [8]:
Arrhythmia.describe()

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,...,452.000000,452.000000,452.000000,452.000000,452.0,452.000000,452.000000,452.000000,452.000000,452.000000
mean,46.471239,0.550885,166.188053,68.170354,88.920354,155.152655,367.207965,169.949115,90.004425,33.676991,...,-0.278982,9.048009,-1.457301,0.003982,0.0,0.514823,1.222345,19.326106,29.473230,3.880531
std,16.466631,0.497955,37.170340,16.590803,15.364394,44.842283,33.385421,35.633072,25.826643,45.431434,...,0.548876,3.472862,2.002430,0.050118,0.0,0.347531,1.426052,13.503922,18.493927,4.407097
min,0.000000,0.000000,105.000000,6.000000,55.000000,0.000000,232.000000,108.000000,0.000000,-172.000000,...,-4.100000,0.000000,-28.600000,0.000000,0.0,-0.800000,-6.000000,-44.200000,-38.600000,1.000000
25%,36.000000,0.000000,160.000000,59.000000,80.000000,142.000000,350.000000,148.000000,79.000000,3.750000,...,-0.425000,6.600000,-2.100000,0.000000,0.0,0.400000,0.500000,11.450000,17.550000,1.000000
50%,47.000000,1.000000,164.000000,68.000000,86.000000,157.000000,367.000000,162.000000,91.000000,40.000000,...,0.000000,8.800000,-1.100000,0.000000,0.0,0.500000,1.350000,18.100000,27.900000,1.000000
75%,58.000000,1.000000,170.000000,79.000000,94.000000,175.000000,384.000000,179.000000,102.000000,66.000000,...,0.000000,11.200000,0.000000,0.000000,0.0,0.700000,2.100000,25.825000,41.125000,6.000000
max,83.000000,1.000000,780.000000,176.000000,188.000000,524.000000,509.000000,381.000000,205.000000,169.000000,...,0.000000,23.600000,0.000000,0.800000,0.0,2.400000,6.000000,88.800000,115.900000,16.000000

In [9]:
Arrhythmia = Arrhythmia.rename(columns={279: "Class"})
print(Arrhythmia.columns)

Index([      0,       1,       2,       3,       4,       5,       6,       7,
             8,       9,
       ...
           270,     271,     272,     273,     274,     275,     276,     277,
           278, 'Class'],
      dtype='object', length=280)

In [10]:
Arrhythmia['Class'].value_counts()

Class
1     245
10     50
2      44
6      25
16     22
3      15
4      15
5      13
9       9
15      5
14      4
7       3
8       2
Name: count, dtype: int64

In [11]:
Arrhythmia['Class'].value_counts(normalize=True) * 100

Class
1     54.203540
10    11.061947
2      9.734513
6      5.530973
16     4.867257
3      3.318584
4      3.318584
5      2.876106
9      1.991150
15     1.106195
14     0.884956
7      0.663717
8      0.442478
Name: proportion, dtype: float64

In [12]:
Arrhythmia.dtypes

0          int64
1          int64
2          int64
3          int64
4          int64
5          int64
6          int64
7          int64
8          int64
9          int64
10        object
11        object
12        object
13        object
14        object
15         int64
16         int64
17         int64
18         int64
19         int64
20         int64
21         int64
22         int64
23         int64
24         int64
25         int64
26         int64
27         int64
28         int64
29         int64
30         int64
31         int64
32         int64
33         int64
34         int64
35         int64
36         int64
37         int64
38         int64
39         int64
40         int64
41         int64
42         int64
43         int64
44         int64
45         int64
46         int64
47         int64
48         int64
49         int64
50         int64
51         int64
52         int64
53         int64
54         int64
55         int64
56         int64
57         int64
58         int64
59         int64
60         int64
61         int64
62         int64
63         int64
64         int64
65         int64
66         int64
67         int64
68         int64
69         int64
70         int64
71         int64
72         int64
73         int64
74         int64
75         int64
76         int64
77         int64
78         int64
79         int64
80         int64
81         int64
82         int64
83         int64
84         int64
85         int64
86         int64
87         int64
88         int64
89         int64
90         int64
91         int64
92         int64
93         int64
94         int64
95         int64
96         int64
97         int64
98         int64
99         int64
100        int64
101        int64
102        int64
103        int64
104        int64
105        int64
106        int64
107        int64
108        int64
109        int64
110        int64
111        int64
112        int64
113        int64
114        int64
115        int64
116        int64
117        int64
118        int64
119        int64
120        int64
121        int64
122        int64
123        int64
124        int64
125        int64
126        int64
127        int64
128        int64
129        int64
130        int64
131        int64
132        int64
133        int64
134        int64
135        int64
136        int64
137        int64
138        int64
139        int64
140        int64
141        int64
142        int64
143        int64
144        int64
145        int64
146        int64
147        int64
148        int64
149        int64
150        int64
151        int64
152        int64
153        int64
154        int64
155        int64
156        int64
157        int64
158        int64
159      float64
160      float64
161      float64
162      float64
163      float64
164      float64
165      float64
166      float64
167      float64
168      float64
169      float64
170      float64
171      float64
172      float64
173      float64
174      float64
175      float64
176      float64
177      float64
178      float64
179      float64
180      float64
181      float64
182      float64
183      float64
184      float64
185      float64
186      float64
187      float64
188      float64
189      float64
190      float64
191      float64
192      float64
193      float64
194      float64
195      float64
196      float64
197      float64
198      float64
199      float64
200      float64
201      float64
202      float64
203      float64
204      float64
205      float64
206      float64
207      float64
208      float64
209      float64
210      float64
211      float64
212      float64
213      float64
214      float64
215      float64
216      float64
217      float64
218      float64
219      float64
220      float64
221      float64
222      float64
223      float64
224      float64
225      float64
226      float64
227      float64
228      float64
229      float64
230      float64
231      float64
232      float64
233      float64
234      float64
235      float64
236      float64
237      float64
238      float64
239      float64
240      float64
241      float64
242      float64
243      float64
244      float64
245      float64
246      float64
247      float64
248      float64
249      float64
250      float64
251      float64
252      float64
253      float64
254      float64
255      float64
256      float64
257      float64
258      float64
259      float64
260      float64
261      float64
262      float64
263      float64
264      float64
265      float64
266      float64
267      float64
268      float64
269      float64
270      float64
271      float64
272      float64
273      float64
274      float64
275      float64
276      float64
277      float64
278      float64
Class      int64
dtype: object

In [13]:
## selecting object columns
object_cols = Arrhythmia.select_dtypes(include=['object']).columns
print(object_cols)

Index([10, 11, 12, 13, 14], dtype='object')

In [14]:
for col in object_cols:
    print(col)
    print(Arrhythmia[col].unique()[:10])
    print("------")

10
['13' '37' '34' '11' '66' '49' '7' '69' '71' '42']
------
11
['64' '-17' '70' '-5' '61' '52' '75' '8' '78' '68']
------
12
['-2' '31' '66' '20' '3' '88' '65' '51' '71' '72']
------
13
['?' '23' '84' '160' '-93' '154' '-144' '-112' '177' '-89']
------
14
['63' '53' '75' '71' '?' '84' '70' '67' '64' '72']
------

In [15]:
for col in Arrhythmia.select_dtypes(include=['object']).columns:
    Arrhythmia[col] = pd.to_numeric(Arrhythmia[col], errors='coerce')

In [16]:
Arrhythmia.dtypes

0          int64
1          int64
2          int64
3          int64
4          int64
5          int64
6          int64
7          int64
8          int64
9          int64
10       float64
11       float64
12       float64
13       float64
14       float64
15         int64
16         int64
17         int64
18         int64
19         int64
20         int64
21         int64
22         int64
23         int64
24         int64
25         int64
26         int64
27         int64
28         int64
29         int64
30         int64
31         int64
32         int64
33         int64
34         int64
35         int64
36         int64
37         int64
38         int64
39         int64
40         int64
41         int64
42         int64
43         int64
44         int64
45         int64
46         int64
47         int64
48         int64
49         int64
50         int64
51         int64
52         int64
53         int64
54         int64
55         int64
56         int64
57         int64
58         int64
59         int64
60         int64
61         int64
62         int64
63         int64
64         int64
65         int64
66         int64
67         int64
68         int64
69         int64
70         int64
71         int64
72         int64
73         int64
74         int64
75         int64
76         int64
77         int64
78         int64
79         int64
80         int64
81         int64
82         int64
83         int64
84         int64
85         int64
86         int64
87         int64
88         int64
89         int64
90         int64
91         int64
92         int64
93         int64
94         int64
95         int64
96         int64
97         int64
98         int64
99         int64
100        int64
101        int64
102        int64
103        int64
104        int64
105        int64
106        int64
107        int64
108        int64
109        int64
110        int64
111        int64
112        int64
113        int64
114        int64
115        int64
116        int64
117        int64
118        int64
119        int64
120        int64
121        int64
122        int64
123        int64
124        int64
125        int64
126        int64
127        int64
128        int64
129        int64
130        int64
131        int64
132        int64
133        int64
134        int64
135        int64
136        int64
137        int64
138        int64
139        int64
140        int64
141        int64
142        int64
143        int64
144        int64
145        int64
146        int64
147        int64
148        int64
149        int64
150        int64
151        int64
152        int64
153        int64
154        int64
155        int64
156        int64
157        int64
158        int64
159      float64
160      float64
161      float64
162      float64
163      float64
164      float64
165      float64
166      float64
167      float64
168      float64
169      float64
170      float64
171      float64
172      float64
173      float64
174      float64
175      float64
176      float64
177      float64
178      float64
179      float64
180      float64
181      float64
182      float64
183      float64
184      float64
185      float64
186      float64
187      float64
188      float64
189      float64
190      float64
191      float64
192      float64
193      float64
194      float64
195      float64
196      float64
197      float64
198      float64
199      float64
200      float64
201      float64
202      float64
203      float64
204      float64
205      float64
206      float64
207      float64
208      float64
209      float64
210      float64
211      float64
212      float64
213      float64
214      float64
215      float64
216      float64
217      float64
218      float64
219      float64
220      float64
221      float64
222      float64
223      float64
224      float64
225      float64
226      float64
227      float64
228      float64
229      float64
230      float64
231      float64
232      float64
233      float64
234      float64
235      float64
236      float64
237      float64
238      float64
239      float64
240      float64
241      float64
242      float64
243      float64
244      float64
245      float64
246      float64
247      float64
248      float64
249      float64
250      float64
251      float64
252      float64
253      float64
254      float64
255      float64
256      float64
257      float64
258      float64
259      float64
260      float64
261      float64
262      float64
263      float64
264      float64
265      float64
266      float64
267      float64
268      float64
269      float64
270      float64
271      float64
272      float64
273      float64
274      float64
275      float64
276      float64
277      float64
278      float64
Class      int64
dtype: object

In [17]:
Arrhythmia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Columns: 280 entries, 0 to Class
dtypes: float64(125), int64(155)
memory usage: 988.9 KB

In [18]:
Arrhythmia.replace("?", np.nan, inplace=True)

In [19]:
(Arrhythmia == "?").sum().sum()

np.int64(0)

In [20]:
Arrhythmia.isnull().sum().sort_values(ascending=False)

13       376
11        22
10         8
12         1
14         1
3          0
4          0
5          0
264        0
249        0
250        0
251        0
252        0
253        0
254        0
255        0
256        0
257        0
258        0
259        0
260        0
261        0
262        0
7          0
24         0
25         0
26         0
27         0
28         0
29         0
30         0
31         0
32         0
33         0
34         0
35         0
36         0
37         0
38         0
39         0
40         0
41         0
42         0
43         0
44         0
45         0
46         0
47         0
48         0
49         0
50         0
51         0
52         0
53         0
54         0
55         0
56         0
57         0
58         0
59         0
60         0
61         0
62         0
63         0
64         0
65         0
66         0
67         0
68         0
69         0
70         0
71         0
72         0
73         0
74         0
75         0
76         0
77         0
78         0
79         0
80         0
81         0
82         0
83         0
84         0
85         0
86         0
87         0
88         0
89         0
90         0
91         0
92         0
93         0
94         0
95         0
96         0
97         0
98         0
99         0
100        0
101        0
102        0
103        0
104        0
105        0
106        0
107        0
108        0
109        0
110        0
111        0
112        0
113        0
114        0
115        0
116        0
117        0
118        0
119        0
120        0
121        0
122        0
123        0
124        0
125        0
126        0
127        0
128        0
129        0
130        0
131        0
132        0
133        0
134        0
135        0
136        0
137        0
138        0
139        0
140        0
141        0
142        0
143        0
144        0
145        0
146        0
147        0
148        0
149        0
150        0
151        0
152        0
153        0
154        0
155        0
156        0
157        0
158        0
159        0
160        0
161        0
162        0
163        0
164        0
165        0
166        0
167        0
168        0
169        0
170        0
171        0
172        0
173        0
174        0
175        0
176        0
177        0
178        0
179        0
180        0
181        0
182        0
183        0
184        0
185        0
186        0
187        0
188        0
189        0
190        0
191        0
192        0
193        0
194        0
195        0
196        0
197        0
198        0
199        0
200        0
201        0
202        0
203        0
204        0
205        0
206        0
207        0
208        0
209        0
210        0
211        0
212        0
213        0
214        0
215        0
216        0
217        0
218        0
219        0
220        0
221        0
222        0
223        0
224        0
225        0
226        0
227        0
228        0
229        0
230        0
231        0
232        0
233        0
234        0
235        0
236        0
237        0
238        0
239        0
240        0
241        0
242        0
243        0
244        0
245        0
246        0
247        0
6          0
265        0
266        0
267        0
268        0
269        0
270        0
271        0
272        0
273        0
274        0
275        0
276        0
277        0
278        0
23         0
248        0
9          0
8          0
Class      0
0          0
1          0
2          0
15         0
16         0
17         0
18         0
19         0
20         0
21         0
22         0
263        0
dtype: int64

In [21]:
y = Arrhythmia['Class']
X = Arrhythmia.drop(columns=['Class'])

In [22]:
print(X.columns)

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       269, 270, 271, 272, 273, 274, 275, 276, 277, 278],
      dtype='object', length=279)

In [23]:
X.columns = range(1, len(X.columns) + 1)

In [24]:
X.columns = range(1, X.shape[1] + 1)
print(X.columns)

RangeIndex(start=1, stop=280, step=1)

In [25]:
X.head()

,1,2,3,4,5,6,7,8,9,10,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,-0.3,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4
1,56,1,165,64,81,174,401,149,39,25,...,-0.5,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8
2,54,0,172,95,138,163,386,185,102,96,...,0.9,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0
3,55,0,175,94,100,202,380,179,143,28,...,0.1,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6
4,75,0,190,80,88,181,360,177,103,-16,...,-0.4,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8

In [26]:
Arrhythmia_clean = X.copy()
Arrhythmia_clean['Class'] = y
Arrhythmia_clean.head(15)

,1,2,3,4,5,6,7,8,9,10,...,271,272,273,274,275,276,277,278,279,Class
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
5,13,0,169,51,100,167,321,174,91,107,...,-0.6,12.2,-2.8,0.0,0.0,0.9,2.2,13.5,31.1,14
6,40,1,160,52,77,129,377,133,77,77,...,0.0,6.5,0.0,0.0,0.0,0.4,1.0,14.3,20.5,1
7,49,1,162,54,78,0,376,157,70,67,...,0.0,8.2,-1.9,0.0,0.0,0.1,0.5,15.8,19.8,1
8,44,0,168,56,84,118,354,160,63,61,...,0.0,7.0,-1.3,0.0,0.0,0.6,2.1,12.5,30.9,1
9,50,1,167,67,89,130,383,156,73,85,...,-0.6,10.8,-1.7,0.0,0.0,0.8,0.9,20.1,25.1,10
10,62,0,170,72,102,135,401,156,83,72,...,-0.5,9.0,-2.0,0.0,0.0,0.8,0.9,12.3,19.3,3
11,45,1,165,86,77,143,373,150,65,12,...,0.0,4.4,-2.2,0.0,0.0,0.5,1.5,4.9,17.2,1
12,54,1,172,58,78,155,382,163,81,-24,...,0.0,6.3,-2.1,0.0,0.0,0.8,0.5,8.8,12.1,10
13,30,0,170,73,91,180,355,157,104,68,...,-0.9,12.3,0.0,0.0,0.0,0.4,2.1,28.5,48.6,6
14,44,1,160,88,77,158,399,163,94,46,...,-0.6,12.4,0.0,0.0,0.0,0.3,1.7,39.2,54.1,1

In [27]:
Arrhythmia_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Columns: 280 entries, 1 to Class
dtypes: float64(125), int64(155)
memory usage: 988.9 KB

In [28]:
Arrhythmia_clean.describe()

,1,2,3,4,5,6,7,8,9,10,...,271,272,273,274,275,276,277,278,279,Class
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,...,452.000000,452.000000,452.000000,452.000000,452.0,452.000000,452.000000,452.000000,452.000000,452.000000
mean,46.471239,0.550885,166.188053,68.170354,88.920354,155.152655,367.207965,169.949115,90.004425,33.676991,...,-0.278982,9.048009,-1.457301,0.003982,0.0,0.514823,1.222345,19.326106,29.473230,3.880531
std,16.466631,0.497955,37.170340,16.590803,15.364394,44.842283,33.385421,35.633072,25.826643,45.431434,...,0.548876,3.472862,2.002430,0.050118,0.0,0.347531,1.426052,13.503922,18.493927,4.407097
min,0.000000,0.000000,105.000000,6.000000,55.000000,0.000000,232.000000,108.000000,0.000000,-172.000000,...,-4.100000,0.000000,-28.600000,0.000000,0.0,-0.800000,-6.000000,-44.200000,-38.600000,1.000000
25%,36.000000,0.000000,160.000000,59.000000,80.000000,142.000000,350.000000,148.000000,79.000000,3.750000,...,-0.425000,6.600000,-2.100000,0.000000,0.0,0.400000,0.500000,11.450000,17.550000,1.000000
50%,47.000000,1.000000,164.000000,68.000000,86.000000,157.000000,367.000000,162.000000,91.000000,40.000000,...,0.000000,8.800000,-1.100000,0.000000,0.0,0.500000,1.350000,18.100000,27.900000,1.000000
75%,58.000000,1.000000,170.000000,79.000000,94.000000,175.000000,384.000000,179.000000,102.000000,66.000000,...,0.000000,11.200000,0.000000,0.000000,0.0,0.700000,2.100000,25.825000,41.125000,6.000000
max,83.000000,1.000000,780.000000,176.000000,188.000000,524.000000,509.000000,381.000000,205.000000,169.000000,...,0.000000,23.600000,0.000000,0.800000,0.0,2.400000,6.000000,88.800000,115.900000,16.000000

In [29]:
PCT_missingness_per_column= 100 * Arrhythmia_clean.isnull().mean().sort_values(ascending=False)
PCT_missingness_per_column

14       83.185841
12        4.867257
11        1.769912
13        0.221239
15        0.221239
4         0.000000
5         0.000000
6         0.000000
265       0.000000
250       0.000000
251       0.000000
252       0.000000
253       0.000000
254       0.000000
255       0.000000
256       0.000000
257       0.000000
258       0.000000
259       0.000000
260       0.000000
261       0.000000
262       0.000000
263       0.000000
8         0.000000
25        0.000000
26        0.000000
27        0.000000
28        0.000000
29        0.000000
30        0.000000
31        0.000000
32        0.000000
33        0.000000
34        0.000000
35        0.000000
36        0.000000
37        0.000000
38        0.000000
39        0.000000
40        0.000000
41        0.000000
42        0.000000
43        0.000000
44        0.000000
45        0.000000
46        0.000000
47        0.000000
48        0.000000
49        0.000000
50        0.000000
51        0.000000
52        0.000000
53        0.000000
54        0.000000
55        0.000000
56        0.000000
57        0.000000
58        0.000000
59        0.000000
60        0.000000
61        0.000000
62        0.000000
63        0.000000
64        0.000000
65        0.000000
66        0.000000
67        0.000000
68        0.000000
69        0.000000
70        0.000000
71        0.000000
72        0.000000
73        0.000000
74        0.000000
75        0.000000
76        0.000000
77        0.000000
78        0.000000
79        0.000000
80        0.000000
81        0.000000
82        0.000000
83        0.000000
84        0.000000
85        0.000000
86        0.000000
87        0.000000
88        0.000000
89        0.000000
90        0.000000
91        0.000000
92        0.000000
93        0.000000
94        0.000000
95        0.000000
96        0.000000
97        0.000000
98        0.000000
99        0.000000
100       0.000000
101       0.000000
102       0.000000
103       0.000000
104       0.000000
105       0.000000
106       0.000000
107       0.000000
108       0.000000
109       0.000000
110       0.000000
111       0.000000
112       0.000000
113       0.000000
114       0.000000
115       0.000000
116       0.000000
117       0.000000
118       0.000000
119       0.000000
120       0.000000
121       0.000000
122       0.000000
123       0.000000
124       0.000000
125       0.000000
126       0.000000
127       0.000000
128       0.000000
129       0.000000
130       0.000000
131       0.000000
132       0.000000
133       0.000000
134       0.000000
135       0.000000
136       0.000000
137       0.000000
138       0.000000
139       0.000000
140       0.000000
141       0.000000
142       0.000000
143       0.000000
144       0.000000
145       0.000000
146       0.000000
147       0.000000
148       0.000000
149       0.000000
150       0.000000
151       0.000000
152       0.000000
153       0.000000
154       0.000000
155       0.000000
156       0.000000
157       0.000000
158       0.000000
159       0.000000
160       0.000000
161       0.000000
162       0.000000
163       0.000000
164       0.000000
165       0.000000
166       0.000000
167       0.000000
168       0.000000
169       0.000000
170       0.000000
171       0.000000
172       0.000000
173       0.000000
174       0.000000
175       0.000000
176       0.000000
177       0.000000
178       0.000000
179       0.000000
180       0.000000
181       0.000000
182       0.000000
183       0.000000
184       0.000000
185       0.000000
186       0.000000
187       0.000000
188       0.000000
189       0.000000
190       0.000000
191       0.000000
192       0.000000
193       0.000000
194       0.000000
195       0.000000
196       0.000000
197       0.000000
198       0.000000
199       0.000000
200       0.000000
201       0.000000
202       0.000000
203       0.000000
204       0.000000
205       0.000000
206       0.000000
207       0.000000
208       0.000000
209       0.000000
210       0.000000
211       0.000000
212       0.000000
213       0.000000
214       0.000000
215       0.000000
216       0.000000
217       0.000000
218       0.000000
219       0.000000
220       0.000000
221       0.000000
222       0.000000
223       0.000000
224       0.000000
225       0.000000
226       0.000000
227       0.000000
228       0.000000
229       0.000000
230       0.000000
231       0.000000
232       0.000000
233       0.000000
234       0.000000
235       0.000000
236       0.000000
237       0.000000
238       0.000000
239       0.000000
240       0.000000
241       0.000000
242       0.000000
243       0.000000
244       0.000000
245       0.000000
246       0.000000
247       0.000000
248       0.000000
7         0.000000
266       0.000000
267       0.000000
268       0.000000
269       0.000000
270       0.000000
271       0.000000
272       0.000000
273       0.000000
274       0.000000
275       0.000000
276       0.000000
277       0.000000
278       0.000000
279       0.000000
24        0.000000
249       0.000000
10        0.000000
9         0.000000
Class     0.000000
1         0.000000
2         0.000000
3         0.000000
16        0.000000
17        0.000000
18        0.000000
19        0.000000
20        0.000000
21        0.000000
22        0.000000
23        0.000000
264       0.000000
dtype: float64

In [30]:
PCT_missingness_per_row = 100 * Arrhythmia_clean.isnull().mean(axis=1).sort_values(ascending=False)
PCT_missingness_per_row

106    0.714286
420    0.714286
66     0.714286
204    0.714286
116    0.714286
54     0.714286
177    0.714286
412    0.714286
193    0.714286
59     0.714286
91     0.714286
219    0.714286
200    0.714286
238    0.714286
212    0.714286
243    0.714286
284    0.714286
279    0.714286
310    0.714286
298    0.714286
372    0.714286
350    0.714286
360    0.714286
4      0.714286
0      0.357143
451    0.357143
50     0.357143
19     0.357143
20     0.357143
21     0.357143
22     0.357143
23     0.357143
24     0.357143
25     0.357143
26     0.357143
27     0.357143
28     0.357143
30     0.357143
31     0.357143
32     0.357143
33     0.357143
34     0.357143
35     0.357143
36     0.357143
37     0.357143
38     0.357143
39     0.357143
40     0.357143
41     0.357143
42     0.357143
43     0.357143
44     0.357143
45     0.357143
46     0.357143
47     0.357143
48     0.357143
49     0.357143
81     0.357143
82     0.357143
51     0.357143
52     0.357143
53     0.357143
55     0.357143
57     0.357143
58     0.357143
60     0.357143
61     0.357143
62     0.357143
63     0.357143
64     0.357143
65     0.357143
96     0.357143
97     0.357143
98     0.357143
67     0.357143
68     0.357143
69     0.357143
70     0.357143
72     0.357143
73     0.357143
74     0.357143
75     0.357143
76     0.357143
77     0.357143
78     0.357143
79     0.357143
80     0.357143
107    0.357143
108    0.357143
109    0.357143
110    0.357143
111    0.357143
113    0.357143
114    0.357143
83     0.357143
84     0.357143
87     0.357143
90     0.357143
92     0.357143
94     0.357143
95     0.357143
121    0.357143
122    0.357143
123    0.357143
124    0.357143
125    0.357143
126    0.357143
127    0.357143
128    0.357143
129    0.357143
130    0.357143
100    0.357143
101    0.357143
102    0.357143
103    0.357143
104    0.357143
105    0.357143
135    0.357143
136    0.357143
137    0.357143
139    0.357143
140    0.357143
141    0.357143
142    0.357143
143    0.357143
144    0.357143
145    0.357143
146    0.357143
115    0.357143
117    0.357143
118    0.357143
119    0.357143
150    0.357143
151    0.357143
152    0.357143
153    0.357143
154    0.357143
155    0.357143
156    0.357143
157    0.357143
159    0.357143
160    0.357143
161    0.357143
162    0.357143
131    0.357143
132    0.357143
133    0.357143
134    0.357143
405    0.357143
406    0.357143
407    0.357143
408    0.357143
409    0.357143
411    0.357143
413    0.357143
414    0.357143
415    0.357143
416    0.357143
417    0.357143
418    0.357143
147    0.357143
148    0.357143
149    0.357143
194    0.357143
163    0.357143
164    0.357143
165    0.357143
166    0.357143
167    0.357143
168    0.357143
169    0.357143
171    0.357143
172    0.357143
173    0.357143
174    0.357143
176    0.357143
178    0.357143
203    0.357143
205    0.357143
206    0.357143
210    0.357143
179    0.357143
180    0.357143
181    0.357143
182    0.357143
183    0.357143
184    0.357143
185    0.357143
186    0.357143
190    0.357143
191    0.357143
192    0.357143
217    0.357143
218    0.357143
419    0.357143
220    0.357143
221    0.357143
222    0.357143
223    0.357143
224    0.357143
225    0.357143
226    0.357143
195    0.357143
196    0.357143
197    0.357143
199    0.357143
421    0.357143
201    0.357143
229    0.357143
230    0.357143
231    0.357143
232    0.357143
233    0.357143
234    0.357143
236    0.357143
422    0.357143
240    0.357143
241    0.357143
242    0.357143
211    0.357143
423    0.357143
214    0.357143
215    0.357143
216    0.357143
257    0.357143
258    0.357143
387    0.357143
390    0.357143
391    0.357143
392    0.357143
393    0.357143
394    0.357143
396    0.357143
397    0.357143
399    0.357143
400    0.357143
401    0.357143
402    0.357143
227    0.357143
228    0.357143
270    0.357143
271    0.357143
272    0.357143
273    0.357143
274    0.357143
425    0.357143
244    0.357143
245    0.357143
246    0.357143
247    0.357143
248    0.357143
249    0.357143
250    0.357143
251    0.357143
253    0.357143
255    0.357143
427    0.357143
286    0.357143
287    0.357143
288    0.357143
289    0.357143
290    0.357143
259    0.357143
261    0.357143
262    0.357143
263    0.357143
264    0.357143
265    0.357143
266    0.357143
267    0.357143
268    0.357143
269    0.357143
300    0.357143
301    0.357143
302    0.357143
303    0.357143
304    0.357143
305    0.357143
306    0.357143
275    0.357143
276    0.357143
277    0.357143
278    0.357143
428    0.357143
280    0.357143
281    0.357143
282    0.357143
283    0.357143
429    0.357143
311    0.357143
312    0.357143
313    0.357143
314    0.357143
315    0.357143
316    0.357143
317    0.357143
318    0.357143
320    0.357143
321    0.357143
292    0.357143
293    0.357143
294    0.357143
431    0.357143
299    0.357143
432    0.357143
373    0.357143
374    0.357143
375    0.357143
377    0.357143
378    0.357143
379    0.357143
381    0.357143
382    0.357143
383    0.357143
384    0.357143
385    0.357143
386    0.357143
307    0.357143
308    0.357143
309    0.357143
433    0.357143
351    0.357143
353    0.357143
325    0.357143
326    0.357143
327    0.357143
329    0.357143
330    0.357143
331    0.357143
332    0.357143
333    0.357143
335    0.357143
336    0.357143
337    0.357143
338    0.357143
371    0.357143
362    0.357143
363    0.357143
364    0.357143
365    0.357143
369    0.357143
339    0.357143
340    0.357143
341    0.357143
342    0.357143
343    0.357143
344    0.357143
345    0.357143
346    0.357143
347    0.357143
348    0.357143
349    0.357143
436    0.357143
437    0.357143
438    0.357143
439    0.357143
441    0.357143
442    0.357143
443    0.357143
444    0.357143
445    0.357143
446    0.357143
447    0.357143
448    0.357143
355    0.357143
358    0.357143
434    0.357143
361    0.357143
3      0.357143
1      0.357143
5      0.357143
6      0.357143
7      0.357143
9      0.357143
10     0.357143
11     0.357143
12     0.357143
13     0.357143
14     0.357143
15     0.357143
16     0.357143
17     0.357143
18     0.357143
435    0.357143
8      0.000000
440    0.000000
449    0.000000
450    0.000000
356    0.000000
357    0.000000
359    0.000000
366    0.000000
367    0.000000
368    0.000000
370    0.000000
352    0.000000
354    0.000000
323    0.000000
324    0.000000
328    0.000000
334    0.000000
376    0.000000
380    0.000000
319    0.000000
322    0.000000
291    0.000000
295    0.000000
296    0.000000
297    0.000000
285    0.000000
260    0.000000
252    0.000000
254    0.000000
256    0.000000
388    0.000000
389    0.000000
395    0.000000
398    0.000000
235    0.000000
237    0.000000
239    0.000000
213    0.000000
198    0.000000
202    0.000000
207    0.000000
208    0.000000
209    0.000000
187    0.000000
188    0.000000
189    0.000000
170    0.000000
175    0.000000
403    0.000000
404    0.000000
410    0.000000
158    0.000000
138    0.000000
120    0.000000
99     0.000000
112    0.000000
85     0.000000
86     0.000000
88     0.000000
89     0.000000
93     0.000000
71     0.000000
56     0.000000
29     0.000000
424    0.000000
426    0.000000
430    0.000000
2      0.000000
dtype: float64

In [31]:
Zero_variance_features=(Arrhythmia_clean.std() == 0).sort_values(ascending=False)
Zero_variance_features

144       True
152       True
165       True
158       True
20        True
157       True
265       True
132       True
133       True
68        True
84        True
142       True
205       True
70        True
275       True
140       True
146       True
188      False
192      False
191      False
190      False
189      False
204      False
187      False
186      False
194      False
185      False
184      False
183      False
193      False
207      False
195      False
196      False
197      False
198      False
199      False
200      False
201      False
181      False
202      False
203      False
206      False
182      False
175      False
180      False
163      False
147      False
148      False
149      False
150      False
151      False
153      False
154      False
155      False
156      False
159      False
160      False
161      False
162      False
164      False
179      False
166      False
167      False
168      False
169      False
170      False
171      False
172      False
173      False
174      False
209      False
176      False
177      False
178      False
208      False
1        False
210      False
254      False
260      False
259      False
258      False
257      False
256      False
255      False
253      False
211      False
252      False
251      False
250      False
249      False
248      False
247      False
261      False
262      False
263      False
264      False
266      False
267      False
268      False
269      False
270      False
271      False
272      False
273      False
274      False
276      False
277      False
278      False
279      False
246      False
245      False
244      False
227      False
213      False
214      False
215      False
216      False
217      False
218      False
219      False
220      False
221      False
222      False
223      False
224      False
225      False
226      False
228      False
243      False
229      False
230      False
231      False
232      False
233      False
234      False
235      False
236      False
237      False
238      False
239      False
240      False
241      False
242      False
212      False
141      False
145      False
52       False
38       False
39       False
40       False
41       False
42       False
43       False
44       False
45       False
46       False
47       False
48       False
49       False
50       False
51       False
53       False
36       False
54       False
55       False
56       False
57       False
58       False
59       False
60       False
61       False
62       False
63       False
64       False
65       False
66       False
67       False
37       False
35       False
71       False
17       False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
18       False
34       False
19       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
30       False
31       False
32       False
33       False
69       False
72       False
143      False
123      False
109      False
110      False
111      False
112      False
113      False
114      False
115      False
116      False
117      False
118      False
119      False
120      False
121      False
122      False
124      False
107      False
125      False
126      False
127      False
128      False
129      False
130      False
131      False
134      False
135      False
136      False
137      False
138      False
139      False
2        False
108      False
106      False
73       False
89       False
74       False
75       False
76       False
77       False
78       False
79       False
80       False
81       False
82       False
83       False
85       False
86       False
87       False
88       False
90       False
105      False
91       False
92       False
93       False
94       False
95       False
96       False
97       False
98       False
99       False
100      False
101      False
102      False
103      False
104      False
Class    False
dtype: bool

In [32]:
Zero_variance_features.shape

(280,)